# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :yaTANK => {
        :box_name => "ubuntu/bionic64",
        :box_version => "20200525.0.0",
        :ip_addr => '192.168.11.102',
        :path => 'ya-tank.sh'
    }, 
}

Vagrant.configure("2") do |config|
    config.vm.box_version = "20200525.0.0"
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "2048"]
                needsController = false
            end#box.vm.provider 
            box.vm.provision "shell", path: boxconfig[:path]
        end#config.vm.define
    end#MACHINES
end #Vagrant.config