# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|   
        config.vm.define "web" do |web|
            web.vm.box = "centos/7"
            web.vm.hostname="web"
            web.vm.network :private_network, ip: "192.168.100.10"
            web.vm.provider "virtualbox" do |vb|
                vb.memory = "512"
                vb.cpus = "1"
            end
        end 



        config.vm.define "log" do |log|
            log.vm.box = "centos/7"
            log.vm.hostname="log"
            log.vm.network :"private_network",  ip: "192.168.100.11"
            log.vm.provider "virtualbox" do |vb|
                vb.memory = "512"
                vb.cpus = "1"
            end
        end



        config.vm.define "elk" do |elk|
            elk.vm.box = "centos/7"
            elk.vm.hostname="elk"
            elk.vm.network :"private_network",  ip: "192.168.100.12"
            elk.vm.provider "virtualbox" do |vb|
                vb.memory = "4096"
                vb.cpus = "1"
            end
        end

   
end